# Generated by Django 3.1 on 2020-09-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlogin',
            name='TCode',
        ),
        migrations.DeleteModel(
            name='TInformation',
        ),
        migrations.DeleteModel(
            name='TLogin',
        ),
    ]
