# Generated by Django 3.1 on 2020-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200901_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinformation',
            name='TMiddleName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
