# Generated by Django 3.1 on 2020-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200901_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinformation',
            name='TMiddleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
