# Generated by Django 3.1 on 2020-09-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200901_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlogin',
            old_name='TCode',
            new_name='Teacher',
        ),
    ]
