# Generated by Django 3.1 on 2020-09-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20200902_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TLogin',
        ),
    ]
