# Generated by Django 3.1 on 2020-09-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_delete_tlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TFirstName', models.CharField(max_length=50)),
                ('TUsername', models.CharField(max_length=50)),
                ('TPassword', models.CharField(max_length=50)),
                ('TCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.tinformation')),
            ],
        ),
    ]
