# Generated by Django 3.1 on 2020-09-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCode', models.CharField(max_length=4)),
                ('TFirstName', models.CharField(max_length=50)),
                ('TMiddleName', models.CharField(max_length=50)),
                ('TLastName', models.CharField(max_length=50)),
                ('TClass', models.IntegerField()),
                ('TSection', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TUsername', models.CharField(max_length=50)),
                ('TPassword', models.CharField(max_length=50)),
                ('TCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classselect.tinformation')),
            ],
        ),
    ]
